### ISSUE TITLE
Example fails with ValueError: loop argument must agree with Future

### ISSUE THREAD

**Issue by tripleee** [mjcaley/aiospamc#169]
I attempted to exercise the example code but I got an error:

Clean slate (MacOS High Sierra, Homebrew Python 3.5.1):

```bash
bash$ python3 -m venv aiotest
... stuff ...

bash$ . ./aiotest/bin/activate

(aiotest) bash$ pip install aiospamc
Collecting aiospamc
  Using cached https://files.pythonhosted.org/packages/38/4f/2f320f2579e42c0bc178b747a8bc2565ead7c3bf8a782ba02dd9cb4a098c/aiospamc-0.4.1-py3-none-any.whl
Installing collected packages: aiospamc
Successfully installed aiospamc-0.4.1

(aiotest) bash$ python
Python 3.5.1 (default, Dec 26 2015, 18:08:53)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> from aiospamc import *
>>> GTUBE = '''Subject: Test spam mail (GTUBE)
... Message-ID: <GTUBE1.1010101@example.net>
........ (etc etc) .......
... XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X
...
... You should send this test mail from an account outside of your network.
... '''
>>> loop = asyncio.new_event_loop()
>>> client = Client(host='localhost')
>>> responses = loop.run_until_complete(asyncio.gather(
...     client.ping(),
...     client.check(GTUBE),
...     client.headers(GTUBE)
... ))
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 317, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 534, in ensure_future
    raise ValueError('loop argument must agree with Future')
ValueError: loop argument must agree with Future
```

Based on https://stackoverflow.com/questions/46806174/python-3-6-and-valueerror-loop-argument-must-agree-with-future I was able to fix this by adding

```python
asyncio.set_event_loop(loop)
```
before attempting to use the client.

**Comment by tripleee** [comment]
Actually, I still wasn't able to actually obtain a result with this change. I'll replace the PR with a new one which actually works for me. Instead of using `set_event_loop`, it uses `get_event_loop` and passes that to the `Client` initializer.
